### ISSUE TITLE
enable dnssec?

### ISSUE THREAD

**Issue by jimmywarting** [OpenWebTorrent/openwebtorrent-www#11]
Hi, I where on a public municipal WiFi today and tried out webtorrent. I wasn't able to establish a connection to tracker.openwebtorrent.com or any other tracker for that matter. 
By just visiting the site I saw that it where blocked by the router/resolver. (as well as many other sites they don't want you to visit) 😞 

Now it doesn't seems like they are blacklisting ip addresses but rather based on the content/domain names. Anything starting with `tracker.*` seemed to blocked and searching for any free online web based proxy didn't work either (literally everything was blocked) so it seems they scan the sites as well (very untrustworthy 😡)

Now I have investigated and learn how to become more anonymous online and hiding your online activity and becoming more secure and don't leak anything to the ISP on the web without using VPN.

I used this site for testing: https://www.cloudflare.com/ssl/encrypted-sni/

- [x] Secure dns - have enabled DNS over HTTPS (DoH) using firefox + Cloudflare 1.1.1.1
- [x] TLS 1.3 - (encrypts the server certificate)
- [x] Encrypted SNI - (using firefox by changing about:config)
- [ ] dnssec still in a flux to me... here is where my question comes in...

it seems like dnssec is working on my firefox browser @ home but the public wifi's resolver failed that test. Either way it seems like i was able to visit more sites than i could do before with safari that didn't have the same level of security.

I have looked into if you can somehow [force your own browser/mac to use dnssec only](https://security.stackexchange.com/questions/106688/can-you-force-your-pc-or-device-to-use-only-dnssec-verified-lookup-results) my knowledge is about the same level as the questioner...

looking at this test results reveals that:
- [internet.nl - openwebtorrent.com](https://en.internet.nl/site/openwebtorrent.com/739759/)
- [internet.nl - tracker.openwebtorrent.com](https://en.internet.nl/site/tracker.openwebtorrent.com/739756/)

...your server dose not handle DNSSec? it this maybe something that you can enable?

---

(sorry if the issue became a bit long - just wanted to provide as much info as possible.)

**Comment by alxhotel** [comment]
Hey @jimmywarting, thanks for all this info. Very interesting!

May I ask what ISP are you using?

Btw, I have enabled DNSSEC in the `openwebtorrent.com` domain:

- [internet.nl - openwebtorrent.com](https://en.internet.nl/site/openwebtorrent.com/743903/)
- [internet.nl - tracker.openwebtorrent.com](https://en.internet.nl/site/tracker.openwebtorrent.com/743904/)

**Comment by jimmywarting** [comment]
Don't remember the exact name but something with [Huddinge](https://www.google.com/maps/place/Huddinge/@59.2123907,17.8776763,11z/data=!3m1!4b1!4m5!3m4!1s0x465f7a75034b25c7:0x5419ee307b18fe38!8m2!3d59.2097726!4d18.052167)

...there is multiple wifi connection throughout the area with same wifi name.

thx, i will try it out later again and see if i can connect to your domain later when i'm in the area.

FYI. I also tried DNS over TLS that is encrypted by default and it operates on another port but that port was blocked by the router 😞

**Comment by jimmywarting** [comment]
Tried it today...
I was able to connect to https://openwebtorrent.com in firefox but not wss://tracker.openwebtorrent.com

**Comment by jimmywarting** [comment]
one possible differences i could find was that openwebtorrent.com have tls 1.3 enabled and tracker.openwebtorrent.com don't

<img width="1115" alt="Skärmavbild 2020-01-13 kl  18 40 55" src="https://user-images.githubusercontent.com/1148376/72278444-4e6a2580-3634-11ea-9022-ed27489d7f9b.png">
<img width="1114" alt="Skärmavbild 2020-01-13 kl  18 40 46" src="https://user-images.githubusercontent.com/1148376/72278446-4e6a2580-3634-11ea-9e2d-7712397a5e85.png">

**Comment by alxhotel** [comment]
Hmm interesting...

I just updated the TLS to 1.3 in `tracker.openwebtorrent.com`

**Comment by jimmywarting** [comment]
Ty, Will inform you later how it goes.

**Comment by jimmywarting** [comment]
Amazing it works now! So happy 😄 
guess they can't see what I'm doing on eg instant.io now

**Comment by jimmywarting** [comment]
ok one thing doe, i had to set `security.tls.version.min` to 4

meaning "Hey server i can only talk this TLS protocol versions, what TLS versions do you support" and then it gets selected from there... my provider downgrade and don't want me to use TLS 1.3 if it sees that my browser supports more versions

but setting the minium lowest supported TLS version to 4 breaks many other webpages.


0
SSL 3.0 is the minimum required / maximum supported encryption protocol. (Default up to FF/TB 33.0 and SM 2.30 for minimum version.)

1
TLS 1.0 is the minimum required / maximum supported encryption protocol. (This is the current default for the minimum required version.)

2
TLS 1.1 is the minimum required / maximum supported encryption protocol.

3
TLS 1.2 is the minimum required / maximum supported encryption protocol. (This is the current default for the maximum supported version.) 

4
TLS 1.3 is the minimum required / maximum supported encryption protocol

**Comment by jimmywarting** [comment]
in essence it would be safer if you disabled older TLS versions but that would mean that IE could not connect to your site at all. I'm not going to ask you to do it but maybe just consider it at least

https://caniuse.com/#search=tls
2020 is the year when browsers are going to remove TLS 1.0 and 1.1

**Comment by alxhotel** [comment]
Yeah, I'm probably going to drop support for TLS 1.0 and 1.1. The less the better xD

This issue leads to me to ask: how many people have dnssec disabled? I feel like it's something useful for everyone

**Comment by jimmywarting** [comment]
> how many people have dnssec disabled? 

I'm as clueless as you are. I'm very new in this territories. 
Some use other protocols like **DNS over TLS (DoT)** and that don't need as many hacks as **DNS over HTTPS (DoH)** 
DoT is new and use another port instead of like 433 and is secure by default.
DoH was a quick hack and required more complicated tools (don't know where ESNI and dnssec stand in both of them)

> I feel like it's something useful for everyone

agree 🙂
