### ISSUE TITLE
Tracker offline

### ISSUE THREAD

**Issue by drakonkat** [OpenWebTorrent/openwebtorrent-www#15]
Hi i always get in some day the message:
![image](https://user-images.githubusercontent.com/17176640/159040956-cff28201-eab5-4e83-ae5c-bdf62142fc31.png)
Is that offline?

**Comment by alxhotel** [comment]
Yep, thanks for the update @drakonkat.

It looks like Fascast tracker has shutdown. I've replaced it with another community tracker.
