### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by dheeraj-rn** [OpenWebTorrent/openwebtorrent-www#6]
I'm getting and invalid URL error when i use the trackers on my BitTorrent client (BitTorrent 7.9.7 build 42331 - 32 bit ) . Need help 
[http://i.imgur.com/xBipy1h.png](url)

**Comment by alxhotel** [comment]
Your BitTorrent client doesn't have an implementation of WebTorrent.

At this moment, you have these WebTorrent clients (with graphical interface):
- Vuze + plugin: http://plugins.vuze.com/details/azwebtorrent
- WebTorrent Desktop: https://webtorrent.io/desktop
