### ISSUE TITLE
Scrape files?

### ISSUE THREAD

**Issue by d33tah** [OpenWebTorrent/openwebtorrent-www#9]
Hi!

I'd like to do some research on what kind of data is accessible through the WebTorrent trackers. Some BitTorrent trackers serve files like those mentioned here:

https://stackoverflow.com/a/39822400/1091116

Could you publish such file for this tracker?

Cheers,
d33tah

**Comment by alxhotel** [comment]
Thanks @d33tah. Interesting feature.

Unfortunately, I don't have too much time these days, but I encourage anyone (including yourself) to make a PR to [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker), so that OpenWebtorrent can benefit from it ;)

**Comment by d33tah** [comment]
Thanks! I'm not a JS dev, but I might try to hack something up. What's the minimum you would like to see for such a PR to get merged?

**Comment by d33tah** [comment]
Also, what's the relationship between https://github.com/OpenWebTorrent/openwebtorrent-tracker and https://github.com/webtorrent/bittorrent-tracker ?

**Comment by alxhotel** [comment]
> What's the minimum you would like to see for such a PR to get merged?

Well, it's not a difficult implementation. I would expect a fully functional feature.

> Also, what's the relationship between https://github.com/OpenWebTorrent/openwebtorrent-tracker and https://github.com/webtorrent/bittorrent-tracker?

[openwebtorrent-tracker](https://github.com/OpenWebTorrent/openwebtorrent-tracker) is a fork from [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker). The current OpenWebtorrent tracker gets updates from [openwebtorrent-tracker](https://github.com/OpenWebTorrent/openwebtorrent-tracker).

**Comment by alxhotel** [comment]
Moved to: [webtorrent/bittorrent-tracker#118](/webtorrent/bittorrent-tracker/issues/239)
